football-app:
  batch-readerQueryLimit: true

spring:
  datasource:
    url: jdbc:h2:mem:football_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy:
          it.kristianp.footballbackendwebapp.hibernate.CustomPhysicalNamingStrategy
